[config]

[templates.nvim]
input_path = 'templates/nvim-colors.json'
output_path = '~/.cache/matugen/colors.json'

[templates.yazi]
input_path = 'templates/yazi-colors.toml'
output_path = '~/.config/yazi/theme.toml'

[templates.btop]
input_path = 'templates/btop-colors.theme'
output_path = '~/.config/btop/themes/matugen.theme'

